apiVersion: v1
kind: Service
metadata:
  name: graphik
  labels:
    app: graphik
spec:
  ports:
    - port: 7820
      name: api
  clusterIP: None
  selector:
    app: graphik
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graphik
spec:
  serviceName: "graphik"
  replicas: 3
  selector:
    matchLabels:
      app: graphik
  template:
    metadata:
      labels:
        app: graphik
    spec:
      containers:
        - name: graphik
          env:
            - name: GRAPHIK_OPEN_ID
              value: https://accounts.google.com/.well-known/openid-configuration
            - name: GRAPHIK_ROOT_USERS
              value: coleman.word@graphikdb.io
            - name: GRAPHIK_ENVIRONMENT
              value: k8s
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: graphikdb/graphik:v1.0.0
          ports:
            - containerPort: 7820
              name: api
          volumeMounts:
            - name: database-storage
              mountPath: /usr/share/graphik/html
  volumeClaimTemplates:
    - metadata:
        name: database-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi